
name: Build Portable EXE

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed --name THE12_ModTranslator main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: THE12_ModTranslator.exe
          path: dist/THE12_ModTranslator.exe
